compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  bad-software:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
